### ISSUE TITLE
Implementar diseño de interfaz de configuración 

### ISSUE THREAD

**Issue by DeveloperOscar** [puyu-pe/puka-ws#2]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Falta el diseño de la interfaz  para la configuración de parametros necesarios para la conexión con bifrost

---

## **Describe the solution you'd like**

*

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

* Migrar el diseño de interfaz de puka-csharp a  puka

**Comment by OscarDevCPP** [comment]
Se implemento el siguiente diseño 
![imagen](https://github.com/puyu-pe/puka/assets/143469741/395371be-a419-4a38-a04f-5a912de3f49c)
