### ISSUE TITLE
Diseñar pestaña de pruebas en el panel de acciones

### ISSUE THREAD

**Issue by DeveloperOscar** [puyu-pe/puka-ws#32]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* En el panel de acciones se necesita una seccion para realizar pruebas a servicios de impresion.
* Se debe poder realizar pruebas a servicios de tipo samba , usb(linux, windows), ethernet , serial , cups ,etc

**Comment by OscarDevCPP** [comment]
Diseño de pestaña de pruebas de impresión

![Image](https://github.com/puyu-pe/puka/assets/143469741/a12d508a-44d1-4605-9ae6-9bb8fd3f3ad0)
