### ISSUE TITLE
Implementar seccion de pruebas en el panel de acciones

### ISSUE THREAD

**Issue by DeveloperOscar** [puyu-pe/puka-ws#33]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Una vez este listo el diseño se debe implementar la seccion de panel de pruebas , y dar la funcionalidad correspondiente

**Comment by OscarDevCPP** [comment]
Diseño de la pestaña , previsualización
![Image](https://github.com/puyu-pe/puka/assets/143469741/c753d2a7-c96a-47ea-8e60-9175c7e0f3c0)

**Comment by OscarDevCPP** [comment]
Diseño final de las  pruebas de impresion
![imagen](https://github.com/puyu-pe/puka/assets/143469741/d95d3907-cb3d-428b-8e04-e59f1ec4a754)
