### ISSUE TITLE
Agregar informacion sobre donde se registran los logs de puka al panel de acciones

### ISSUE THREAD

**Issue by DeveloperOscar** [puyu-pe/puka-ws#40]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

*  debe implementarse una forma de poder copiar al portapaleles la ruta de los logs para poder acceder a ellos de forma rapida

**Comment by OscarDevCPP** [comment]
Se intento abrir el directorio de logs directamente desde java, una solucion global para abrir el explorador de archivos en la ruta especificada. sin embargo la solucion no es multiplataforma, no es compatible en todos los sistema operativos.

**Comment by OscarDevCPP** [comment]
La opcion que se esta tomando en cuenta es que se cree un menuitem para el trayicons con la funcionalidad de copiar al portapaleles la ruta de los logs
