### ISSUE TITLE
[Bug] Empaquetado final en windows , no imprime boletas

### ISSUE THREAD

**Issue by DeveloperOscar** [puyu-pe/puka-ws#48]
# **🐞 Bug Report**

## **Describe the bug**

* Despues de ejecutar los script de  jpackage se genera un instalador , el cual se usa para instalar la aplicacion.
* La aplicacion instalada no imprime boletas
* El error esta en que faltaba incluir un modulo mas al manual_modules del script "jdk.charsets", este script era necesario para que la libreria JTicketDesing generara los codigo QR.
* Resulta que este modulo faltante hacia que la escritura en el buffer de la impresora no se llegara a concretar y por eso solo llegaba a la cola de impresion pero no se liberaba por que el codigo se detenia justo en la generacion del codigo QR.

### **Expected behaviour**

* La solucion es simple, se debe agregar el modulo faltante al script de instalador windows. Sin embargo llegar a encontrar este modulo requirio mucho tiempo de prueba y error intentando averiguar cual era ese modulo faltante.

**Comment by velnae** [comment]
Entonces ya podremos usar el instalador sin problemas? 🥲

**Comment by DeveloperOscar** [comment]
La version de puka que soluciona este error es apartir de la  0.2.1. que aun falta lanzar su version release.
