### ISSUE TITLE
Actualizar panel de pruebas de impresion y agregar opcion para normalizar texto - Considerar los cambios de JTicketDesing en SweetTicketPrinter

### ISSUE THREAD

**Issue by OscarDevCPP** [puyu-pe/puka-ws#53]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* JticketDesign se actualizo y ya no soporta un segundo parametro metadatos, la construcciones de los parametros de compatibilidad ahora es responsabilidad de la librerria.
* Ahora JTicketDesing espera que si hay un parametro de compatibilidad  venga dentro de la propiedad properties dentro del objeto printer 
* En consecuencia se debe actualizar el modulo de pruebas de impresion para que inyecte esos parametros compatibilidad en el objeto printer

* Actualizar JTicketPrinter segun los cambios de JTicketDesing

---

## **Describe the solution you'd like**

*

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by velnae** [comment]
Limpiar o sanear
